name: cuda-env
store: /alternative-point
system: hohgant
spack:
    repo: https://github.com/spack/spack.git
    commit: 6408b51
mirror:
    key: /home/bob/veryprivate.key
    enable: True
modules: False
