name: Stackinator CI

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bootstrap
      run: |
        ./bootstrap.sh
    - name: Generic Unittests
      run: |
        ./test_stackinator.py
