gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11.3.0
  unify: true
  specs:
  - osu-micro-benchmarks@5.9
  - hdf5 +mpi
  mpi:
    spec: cray-mpich
    gpu: false
tools:
  compiler:
      - toolchain: gcc
        spec: gcc@11.3.0
  unify: true
  specs:
  - cmake
