mirror:
  enable: true
  key: /scratch/e1000/bcumming/uenv-cache/push-key.gpg
name: host-example
spack:
  commit: releases/v0.20
  repo: https://github.com/spack/spack.git
store: /user-environment
system: hohgant

