name: Deploy and Publish Stackinator to PyPI

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    if: github.repository == 'eth-cscs/stackinator'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Generate dist packages
        run: |
          python -m pip install --upgrade pip setuptools build
          python -m build
      - name: Publish Stackinator to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
